var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/lighter-sof/[id]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__01k10ix._.js")
R.c("server/chunks/ssr/0r9g_0dvju6r._.js")
R.c("server/chunks/ssr/0r9g_next_dist_esm_build_templates_app-page_0w-49po.js")
R.c("server/chunks/ssr/[root-of-the-server]__0f1nhar._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0p6ktc0._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0uvzs4p._.js")
R.c("server/chunks/ssr/0r9g_next_dist_client_components_02pzh0k._.js")
R.c("server/chunks/ssr/0r9g_next_dist_client_components_builtin_forbidden_0hywuao.js")
R.c("server/chunks/ssr/0r9g_next_dist_client_components_builtin_unauthorized_059~5ae.js")
R.c("server/chunks/ssr/0r9g_next_dist_client_components_builtin_global-error_06bh~5g.js")
R.c("server/chunks/ssr/frontend_src_0guo.k.._.js")
R.c("server/chunks/ssr/frontend_src_components_ui_skeleton_tsx_0r8-61m._.js")
R.c("server/chunks/ssr/frontend__next-internal_server_app_lighter-sof_[id]_page_actions_0d-7v6o.js")
R.m(69954)
module.exports=R.m(69954).exports
