// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/import-contracts/[id]" | "/lighter-sof" | "/lighter-sof/[id]" | "/lighter-sof/new" | "/login" | "/master-data" | "/master-data/ghats" | "/master-data/lighters" | "/master-data/locations" | "/master-data/mother-vessels" | "/master-data/organization-types" | "/master-data/organizations" | "/master-data/products" | "/master-data/sof-event-types" | "/master-data/users" | "/mother-sof" | "/mother-sof/[id]" | "/mother-sof/new" | "/mother-vessel-reports" | "/reports" | "/signup" | "/trips" | "/vessel-sof" | "/vessel-sof/discharge" | "/vessel-sof/events" | "/vessel-sof/laytime" | "/vessel-sof/overview"
type PageRoutes = never
type LayoutRoutes = "/" | "/master-data"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/import-contracts/[id]": { "id": string; }
  "/lighter-sof": {}
  "/lighter-sof/[id]": { "id": string; }
  "/lighter-sof/new": {}
  "/login": {}
  "/master-data": {}
  "/master-data/ghats": {}
  "/master-data/lighters": {}
  "/master-data/locations": {}
  "/master-data/mother-vessels": {}
  "/master-data/organization-types": {}
  "/master-data/organizations": {}
  "/master-data/products": {}
  "/master-data/sof-event-types": {}
  "/master-data/users": {}
  "/mother-sof": {}
  "/mother-sof/[id]": { "id": string; }
  "/mother-sof/new": {}
  "/mother-vessel-reports": {}
  "/reports": {}
  "/signup": {}
  "/trips": {}
  "/vessel-sof": {}
  "/vessel-sof/discharge": {}
  "/vessel-sof/events": {}
  "/vessel-sof/laytime": {}
  "/vessel-sof/overview": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/master-data": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
