// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../src/app/import-contracts/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/import-contracts/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/import-contracts/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/lighter-sof/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lighter-sof/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/lighter-sof/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/lighter-sof/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lighter-sof/new">> = Specific
  const handler = {} as typeof import("../../src/app/lighter-sof/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/lighter-sof/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lighter-sof">> = Specific
  const handler = {} as typeof import("../../src/app/lighter-sof/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/master-data/ghats/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/master-data/ghats">> = Specific
  const handler = {} as typeof import("../../src/app/master-data/ghats/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/master-data/lighters/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/master-data/lighters">> = Specific
  const handler = {} as typeof import("../../src/app/master-data/lighters/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/master-data/locations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/master-data/locations">> = Specific
  const handler = {} as typeof import("../../src/app/master-data/locations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/master-data/mother-vessels/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/master-data/mother-vessels">> = Specific
  const handler = {} as typeof import("../../src/app/master-data/mother-vessels/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/master-data/organization-types/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/master-data/organization-types">> = Specific
  const handler = {} as typeof import("../../src/app/master-data/organization-types/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/master-data/organizations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/master-data/organizations">> = Specific
  const handler = {} as typeof import("../../src/app/master-data/organizations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/master-data/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/master-data">> = Specific
  const handler = {} as typeof import("../../src/app/master-data/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/master-data/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/master-data/products">> = Specific
  const handler = {} as typeof import("../../src/app/master-data/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/master-data/sof-event-types/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/master-data/sof-event-types">> = Specific
  const handler = {} as typeof import("../../src/app/master-data/sof-event-types/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/master-data/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/master-data/users">> = Specific
  const handler = {} as typeof import("../../src/app/master-data/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/mother-sof/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mother-sof/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/mother-sof/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/mother-sof/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mother-sof/new">> = Specific
  const handler = {} as typeof import("../../src/app/mother-sof/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/mother-sof/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mother-sof">> = Specific
  const handler = {} as typeof import("../../src/app/mother-sof/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/mother-vessel-reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mother-vessel-reports">> = Specific
  const handler = {} as typeof import("../../src/app/mother-vessel-reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports">> = Specific
  const handler = {} as typeof import("../../src/app/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../src/app/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/trips/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/trips">> = Specific
  const handler = {} as typeof import("../../src/app/trips/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/vessel-sof/discharge/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vessel-sof/discharge">> = Specific
  const handler = {} as typeof import("../../src/app/vessel-sof/discharge/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/vessel-sof/events/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vessel-sof/events">> = Specific
  const handler = {} as typeof import("../../src/app/vessel-sof/events/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/vessel-sof/laytime/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vessel-sof/laytime">> = Specific
  const handler = {} as typeof import("../../src/app/vessel-sof/laytime/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/vessel-sof/overview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vessel-sof/overview">> = Specific
  const handler = {} as typeof import("../../src/app/vessel-sof/overview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/vessel-sof/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vessel-sof">> = Specific
  const handler = {} as typeof import("../../src/app/vessel-sof/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/master-data/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/master-data">> = Specific
  const handler = {} as typeof import("../../src/app/master-data/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
