export const DEFAULT_SOF_PAGE_SIZE = 25;
export const MAX_SOF_PAGE_SIZE = 100;

export const SOF_STATUS_FLOW = {
  DRAFT: ["PENDING_VERIFICATION", "DISPUTED", "CLOSED"],
  PENDING_VERIFICATION: ["VERIFIED", "DISPUTED", "DRAFT"],
  VERIFIED: ["APPROVED", "DISPUTED"],
  APPROVED: ["CLOSED", "DISPUTED"],
  DISPUTED: ["DRAFT", "PENDING_VERIFICATION", "VERIFIED", "CLOSED"],
  CLOSED: []
} as const;
