var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/mother-sof/[id]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0n~b1er._.js")
R.c("server/chunks/ssr/0r9g_0dvju6r._.js")
R.c("server/chunks/ssr/0r9g_next_dist_esm_build_templates_app-page_025hsg3.js")
R.c("server/chunks/ssr/[root-of-the-server]__0f1nhar._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0p6ktc0._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0uvzs4p._.js")
R.c("server/chunks/ssr/0r9g_next_dist_client_components_02pzh0k._.js")
R.c("server/chunks/ssr/0r9g_next_dist_client_components_builtin_forbidden_0hywuao.js")
R.c("server/chunks/ssr/0r9g_next_dist_client_components_builtin_unauthorized_059~5ae.js")
R.c("server/chunks/ssr/0r9g_next_dist_client_components_builtin_global-error_06bh~5g.js")
R.c("server/chunks/ssr/frontend_src_13zra.q._.js")
R.c("server/chunks/ssr/frontend_src_components_ui_skeleton_tsx_0r8-61m._.js")
R.c("server/chunks/ssr/frontend__next-internal_server_app_mother-sof_[id]_page_actions_09zw8eq.js")
R.m(96703)
module.exports=R.m(96703).exports
