var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/vessel-sof/discharge/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0mktnhh._.js")
R.c("server/chunks/ssr/0r9g_next_dist_esm_build_templates_app-page_0n4ia4c.js")
R.c("server/chunks/ssr/0r9g_0dvju6r._.js")
R.c("server/chunks/ssr/0r9g_next_dist_0lv0vf~._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0f1nhar._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0p6ktc0._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0uvzs4p._.js")
R.c("server/chunks/ssr/0r9g_next_dist_client_components_02pzh0k._.js")
R.c("server/chunks/ssr/0r9g_next_dist_client_components_builtin_forbidden_0hywuao.js")
R.c("server/chunks/ssr/0r9g_next_dist_client_components_builtin_unauthorized_059~5ae.js")
R.c("server/chunks/ssr/0r9g_next_dist_client_components_builtin_global-error_06bh~5g.js")
R.c("server/chunks/ssr/frontend__next-internal_server_app_vessel-sof_discharge_page_actions_0e6fao..js")
R.m(34913)
module.exports=R.m(34913).exports
